Blogging/routes/web.php
<?php

use App\Http\Controllers\Admin\AdminAuthController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\GuestPostController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\User\UserAuthController;
use App\Http\Controllers\User\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [GuestPostController::class, 'index'])->name('index');
Route::get('/view_blog/{post}', [GuestPostController::class, 'show'])->name('view_blog');
Route::resource('/comment', CommentController::class);



Auth::routes();

// USER ROUTES
Route::prefix('user')->name('user.')->group(function(){

    Route::middleware(['guest:web'])->group(function(){
        Route::view('/login', 'dashboard.user.login')->name('login');
        Route::view('/register', 'dashboard.user.register')->name('register');
        Route::post('/create', [UserAuthController::class, 'create'])->name('create');
        Route::post('/login', [UserAuthController::class, 'submit'])->name('submit');

    });

    Route::middleware(['auth:web'])->group(function(){
        Route::get('/home', [UserController::class, 'countShow'])->name('home');
        Route::resource('/blog', PostController::class);
        Route::post('/logout', [UserAuthController::class, 'logout'])->name('logout');
        Route::get('your-posts', [UserController::class, 'blogShow'])->name('your_posts');
        // Route::view('create-blog', 'dashboard.user.create_blog')->name('create_blog');
    });
});

// ADMIN ROUTES
Route::prefix('admin')->name('admin.')->group(function(){
       
    Route::middleware(['guest:admin'])->group(function(){
          Route::view('/login','dashboard.admin.login')->name('login');
          Route::post('/login',[AdminAuthController::class,'submit'])->name('submit');
    });

    Route::middleware(['auth:admin'])->group(function(){
        Route::view('/home','dashboard.admin.home')->name('home');
        Route::get('/manage_posts', [AdminController::class, 'show_posts'])->name('manage_posts');
        Route::get('/manage_users', [AdminController::class, 'show_users'])->name('manage_users');
        Route::get('/single_post/{id}', [AdminController::class, 'single_post'])->name('single_post');
        Route::delete('/post_delete/{id}', [AdminController::class, 'post_delete'])->name('post_delete');
        Route::delete('/user_delete/{id}', [AdminController::class, 'user_delete'])->name('user_delete');
        Route::post('/post_status/{id}', [AdminController::class, 'post_status'])->name('post_status');
        Route::get('/day-wise-report', [AdminController::class, 'report_get'])->name('report_get');
        // Route::post('/day-wise-report', [AdminController::class, 'report_result'])->name('report_result');
        Route::post('/logout',[AdminAuthController::class,'logout'])->name('logout');
    });

});

Blogging/app/Http/Controllers/Admin/AdminController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

use App\Models\Post;
use App\Models\User;
use Carbon\Carbon;

class AdminController extends Controller
{
    /**
     * Showing All Posts to admin 
     */
    public function show_posts()
    {
        $blogs = Post::OrderBy('updated_at', 'DESC')->get();
        return view('dashboard.admin.manage_posts',[
            'blogs' => $blogs
        ]);
    }

    /**
     * Showing All Users to admin 
     */
    public function show_users()
    {
        $users = User::OrderBy('updated_at', 'DESC')->get();
        return view('dashboard.admin.manage_users',[
            'users' => $users
        ]);
    }

    /**
     * Delete Specific Post from admin dashboard
     */
    public function post_delete($id)
    {

        $post = Post::where('id', $id)->first();
        Storage::disk('public')->delete('images/'.$post->image_path);
        $post->delete();
        return redirect()->back()->with('message', 'Blog has been deleted!');
    }

    /**
     * Delete Specific User from admin dashboard
     */

    public function user_delete($id)
    {

        $post = User::where('id', $id)->first();
        $post->delete();
        return redirect()->back()->with('message', 'User has been deleted!');
    }

    /**
     * Viewing Specific Post from admin dashboard
     */

    public function single_post($id)
    {

        $post = Post::where('id', $id)->first();
        return view('dashboard.admin.view_post', [
            'post' => $post
        ]);

    }

    /**
     * Post Approval/Decline from admin dashboard
     */
    public function post_status(Request $request, $id)
    {
        $request->validate([
            'status' => 'required',

        ]);

        Post::where('id', $id)->update([
            'status' => $request->status,
        ]);
        return redirect()->back()->with('message', 'Blog Status updated!');
    }

    public function report_get(Request $request)
    {
        // $from = date('2022-06-19');
        // $to = date('2022-06-20');
        // $result = Post::whereBetween('created_at', [$from, Carbon::parse($to)->endOfDay(),])->where('user_id', 1)->get();
        
        // $from = $request->from;
        // $to = $request->to;

        // $user = $request->user;
        // $status_val = $request->status;

        
        $from = request('from', null);
        $to = request('to',null);
        $user = request('user',null);
        $status_val = request('status', null);
        $type = request('type', 'comment');
        
        $users = User::all();
        
        // $results = Post::withCount(['comments' => function ($query) use($from,$to){
        //     $query->whereBetween('comments.created_at', [$from, Carbon::parse($to)->endOfDay(),]);
        // }])->where('user_id', $user)->where('status', $status_val)->get();

        $results = Post::when($request->has('user'), function($query) use($user){
            $query->where('user_id', $user);
        })
        ->when($request->has('status'), function($query) use($status_val){
            $query->where('status', $status_val);
        })
        ->when($from && $to, function($query) use($from, $to, $type){
            if($type == 'post') {
                $query->whereBetween('posts.created_at', [$from.' 00:00:00', $to.' 23:59:59'])->withCount('comments');
            } else {
                $query->withCount(['comments'=> function($q)use($from, $to){
                    $q->whereBetween('comments.created_at', [$from.' 00:00:00', $to.' 23:59:59']);
                }]);
            }
        })
        ->paginate(1);

        return view('dashboard.admin.report', [
            'results' => $results,
            'users' => $users,
        ]);
        return dd($results);
    }

    // public function report_result(Request $request)
    // {


    //     $from = $request->from;
    //     $to = $request->to;

    //     // $from = date('2022-06-22');
    //     // $to = date('2022-06-22');

    //     $user = $request->user;
    //     $status_val = $request->status;
    //     // $results = Post::whereBetween('created_at', [$from, Carbon::parse($to)->endOfDay(),])->where('user_id', $user)->get();
        
    //     $users = User::all();

    //     // $results = Post::whereHas('comments', function($q) use($from,$to){
    //     //     $q->whereBetween('created_at', [$from, Carbon::parse($to)->endOfDay(),]);
    //     // })->get();
    //         $results = Post::withCount(['comments' => function ($query) use($from,$to){
    //             $query->whereBetween('comments.created_at', [$from, Carbon::parse($to)->endOfDay(),]);
    //         }])->where('user_id', $user)->where('status', $status_val)->get();

    //     return view('dashboard.admin.report', [
    //         'results' => $results,
    //         'users' => $users,
    //     ]);

    //     // return dd($test);
    // }

}

Blogging/resources/views/dashboard/admin/home.blade.php
@extends('layouts.master')
@section('content')
    
<div class="container-fluid">
    <div class="row">
     
      @include('layouts.sidebar')

      <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
       <div class="conatiner">
          <div class="row">
              <div class="col-md-12">

              </div>
          </div>
       </div>
      </main>
    </div>
  </div>

@endsection

Blogging/resources/views/dashboard/admin/login.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Login</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
</head>
<body>
<div class="container">
        <div class="row">
            <div class="col-md-4 offset-md-4" style="margin-top: 45px">
                 <h4>Admin Login</h4><hr>
                 <form action="{{ route('admin.submit') }}" method="post">
                    @if (Session::get('fail'))
                        <div class="alert alert-danger">
                            {{ Session::get('fail') }}
                        </div>
                    @endif
                    @csrf
                     <div class="form-group">
                         <label for="email">Email</label>
                         <input type="text" class="form-control" name="email" placeholder="Enter email address" value="{{ old('email') }}">
                         <span class="text-danger">@error('email'){{ $message }}@enderror</span>
                     </div>
                     <div class="form-group">
                         <label for="password">Password</label>
                         <input type="password" class="form-control" name="password" placeholder="Enter password" value="{{ old('password') }}">
                         <span class="text-danger">@error('password'){{ $message }}@enderror</span>
                     </div>
                     <div class="form-group">
                         <button type="submit" class="btn btn-primary">Login</button>
                     </div>
                 </form>
            </div>
        </div>
    </div>
</body>
</html>

Blogging/resources/views/dashboard/admin/manage_posts.blade.php
@extends('layouts.master')
@section('content')
    
<div class="container-fluid">
    <div class="row">
     
      @include('layouts.sidebar')

      <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
       <div class="conatiner">
          <div class="row">
              <div class="col-md-12">
                @if (Session::get('message'))
                <div class="alert alert-success">
                    {{ Session::get('message') }}
                </div>
            @endif
                <table class="table table-striped" id="myTable_manage">
                    <thead>
                      <tr>
                        <th>Title</th>
                        <th>Author</th>
                        <th>Published</th>
                        <th>Approval</th>
                        <th class="text-center">Action</th>
                      </tr>
                    </thead>
                    <tbody>
                        @foreach ($blogs as $blog)
                        <tr>
                            <td>{{ \Illuminate\Support\Str::limit($blog->title, 30, $end='...')}}</td>
                            <td>{{ucfirst($blog->user->name)}}</td>
                            <td>{{ date('jS M Y', strtotime($blog->created_at)) }}</td>
                            <td>@if ($blog->status == 1)
                              <span class="badge badge-pill badge-primary">Approved</span>
                            @elseif ($blog->status == 2)
                            <span class="badge badge-pill badge-danger">Declined</span>
                            @elseif ($blog->status == 0)
                            <span class="badge badge-pill badge-warning">Pending</span>
                            @endif</td>
                            <td class="text-ceneter"><a href="" class="btn btn-info btn-sm" data-toggle="modal" data-target="#myModal2{{$blog->id}}">Edit</a> <a href="{{route('admin.single_post', $blog->id)}}" class="btn btn-success btn-sm">View</a> <a href="" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#myModal{{$blog->id}}">Delete</a></td>
                          </tr>
  <!-- The Modal Delete -->
  <div class="modal fade" id="myModal{{$blog->id}}">
    <div class="modal-dialog modal-sm">
      <div class="modal-content">
      
        <!-- Modal Header -->
        <div class="modal-header">
          <h4 class="modal-title">Delete Blog</h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        
        <!-- Modal body -->
        <div class="modal-body">
          Are you sure want to delete?
        </div>
        
        <!-- Modal footer -->
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <form action="{{route('admin.post_delete', $blog->id)}}" method="post">
            @method('delete')
            @csrf
            <button type="submit" class="btn btn-danger">Delete</button>
          </form>
        </div>
        
      </div>
    </div>
  </div>

  <!-- The Modal Status Change -->
  <div class="modal fade" id="myModal2{{$blog->id}}">
    <div class="modal-dialog modal-sm">
      <div class="modal-content">
      
        <!-- Modal Header -->
        <div class="modal-header">
          <h4 class="modal-title">Approval of Blog</h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        
        <!-- Modal body -->
        <div class="modal-body">
          <form action="{{route('admin.post_status', $blog->id)}}" method="post">
            @csrf
          <div class="form-group">
            <label for="sel1">Select Status:</label>
          <select name="status" id="" class="form-control">
            <option value="0">Pending</option>
            <option value="1">Approve</option>
            <option value="2">Decline</option>
          </select>
          </div>
        </div>
        
        <!-- Modal footer -->
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-danger">Submit</button>
          </form>
        </div>
        
      </div>
    </div>
  </div>
                        @endforeach
                    </tbody>
                  </table>
              </div>
          </div>
       </div>
      </main>
    </div>
  </div>

  
@endsection

Blogging/resources/views/dashboard/admin/manage_users.blade.php
@extends('layouts.master')
@section('content')
    
<div class="container-fluid">
    <div class="row">
     
      @include('layouts.sidebar')

      <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
       <div class="conatiner">
          <div class="row">
              <div class="col-md-12">
                @if (Session::get('message'))
                <div class="alert alert-success">
                    {{ Session::get('message') }}
                </div>
            @endif
                <table class="table table-striped" id="myTable">
                    <thead>
                      <tr>
                        <th>Author Name</th>
                        <th>Email</th>
                        <th>Join at</th>
                        <th>Action</th>
                      </tr>
                    </thead>
                    <tbody>
                        @foreach ($users as $user)
                        <tr>
                            <td>{{ucfirst($user->name)}}</td>
                            <td>{{$user->email}}</td>
                            <td>{{ date('jS M Y', strtotime($user->created_at)) }}</td>
                            <td><a href="" class="btn btn-danger" data-toggle="modal" data-target="#myModal{{$user->id}}">Delete</a></td>
                          </tr>
  <!-- The Modal -->
  <div class="modal fade" id="myModal{{$user->id}}">
    <div class="modal-dialog modal-sm">
      <div class="modal-content">
      
        <!-- Modal Header -->
        <div class="modal-header">
          <h4 class="modal-title">Delete User</h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        
        <!-- Modal body -->
        <div class="modal-body">
          Are you sure want to delete?
        </div>
        
        <!-- Modal footer -->
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <form action="{{route('admin.user_delete', $user->id)}}" method="post">
            @method('delete')
            @csrf
            <button type="submit" class="btn btn-danger">Delete</button>
          </form>
        </div>
        
      </div>
    </div>
  </div>
                        @endforeach
                    </tbody>
                  </table>
              </div>
          </div>
       </div>
      </main>
    </div>
  </div>

  
@endsection

Blogging/resources/views/dashboard/admin/report.blade.php
@extends('layouts.master')
@section('content')
    
<div class="container-fluid">
    <div class="row">
     
      @include('layouts.sidebar')

      <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
       <div class="conatiner">
          <div class="row">
              <div class="col-md-12">
                @if (Session::get('message'))
                <div class="alert alert-success">
                    {{ Session::get('message') }}
                </div>
            @endif
                <form action="{{route('admin.report_get')}}" method="get">
                    <div class="form-group">
                        <div class='input-group date' id='datetimepicker'>
                        <div class="col">
                            <input type='date' class="form-control"  name="from" value="{{request()->from}}"/>
                        </div>
                        <div class="col">
                            <input type='date' class="form-control" name="to" value="{{request()->to}}"/>
                        </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class='input-group'>
                            <div class="col">
                                <select name="user" id="" class="form-control">
                                    @foreach ($users as $user)
                                        <option value="{{$user->id}}" @if(request()->user == $user->id) selected @endif>{{ucfirst($user->name)}}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="col">
                                <select name="status" id="" class="form-control">
                                        <option value="0" @if(request()->status == '0') selected @endif>Pending</option>
                                        <option value="1" @if(request()->status == '1') selected @endif>Approved</option>
                                        <option value="2" @if(request()->status == '2') selected @endif>Declined</option>
                                </select>
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class='input-group'>
                            <div class="col">
                                <select name="type" id="" class="form-control">
                                    <option value="post" @if(request()->type == 'post') selected @endif>Posts</option>
                                    <option value="comment" @if(request()->type == 'comment') selected @endif>Comments</option>
                            </select>
                            </div>
                            <div class="col">
                                <input type="submit" class="btn btn-primary btn-block" value="Submit">
                            </div>
                        </div>
                    </div>

                </form>

                <table class="table table-striped" id="myTable">
                    <thead>
                      <tr>
                        <th>Title</th>
                        <th>Author</th>
                        <th>Status</th>
                        <th>Comments</th>
                      </tr>
                    </thead>
                    <tbody>

                        @foreach ($results as $result)
                        <tr>
                            <td>{{$result->title}}</td>
                            <td>{{ucfirst($result->user->name)}}</td>
                            <td>@if ($result->status == 0)
                                Pending
                            @elseif ($result->status == 1)
                                Approved
                            @elseif ($result->status == 2)
                                Declined
                            @endif</td>
                            <td>{{$result->comments_count}}</td>
                         </tr>
                        @endforeach

                    </tbody>
                  </table>
                {{$results->withQueryString()->links()}}
              </div>
          </div>
       </div>
      </main>
    </div>
  </div>

  
@endsection

Blogging/resources/views/dashboard/admin/view_post.blade.php
@extends('layouts.master')
@section('content')
    
<div class="container-fluid">
    <div class="row">
     
      @include('layouts.sidebar')

      <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
       <div class="conatiner">
          <div class="row">
              <div class="col-md-12">
                <div class="conatiner">
                  <div class="row">
                   
                      <div class="col-md-12">
                        @if (Session::get('message'))
                        <div class="alert alert-success">
                            {{ Session::get('message') }}
                        </div>
                    @endif
                        <div class="jumbotron">
                            <div class="container">
                              <h1 class="display-3">{{$post->title}}</h1>
                              <p>Posted By: {{ ucfirst($post->user->name) }}</p>
                              <p>Published On: {{ date('jS M Y', strtotime($post->created_at)) }}</p>
                              @if (isset(Auth::user()->id) && Auth::user()->id == $post->user_id)
                              <form action="{{route('user.blog.destroy', $post->slug)}}" method="post">
                                @csrf
                                @method('delete')
                               <button type="submit" class="btn btn-danger">Delete Blog</button>
                              </form>                          
                              @endif
                              <hr>
                              <p>{{$post->description}}</p>
                              <hr>
                              @guest
                                  <h6 style="text-align: center; padding-top:15px">Please <a href="{{route('user.login')}}"><b>Log in</b></a> to comment<h6>
                              @endguest
                            </div>
                          </div>
                          <h4>Comments</h4>
                          @foreach ($post->comments as $comment)
                          <div class="card mb-2">
                            <div class="card-body">
                              <h4 class="card-title">{{ucfirst($comment->user->name)}}</h4>
                              <p class="card-text">{{$comment->comment}}</p>
                               @if (isset(Auth::user()->id) && Auth::user()->id == $comment->user_id && (!auth()->user()->isAdmin))
                               <button type="submit" class="btn btn-success btn-sm" data-toggle="modal" data-target="#myModal{{$comment->id}}">Edit</button>
                               <form action="{{route('comment.destroy', $comment->id)}}" method="post">
                                 @csrf
                                 @method('delete')
                                 <button type="submit" class="btn btn-danger btn-sm mt-2">Delete</button>
                              </form>                          
                              @endif
                            </div>
                          </div>
                          <!-- The Modal -->
        <div class="modal" id="myModal{{$comment->id}}">
          <div class="modal-dialog">
            <div class="modal-content">
        
              <!-- Modal Header -->
              <div class="modal-header">
                <h4 class="modal-title">Your Comment</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
              </div>
        
              <!-- Modal body -->
              <div class="modal-body">
                <form action="{{route('comment.update', $comment->id)}}" method="post">
                  @csrf
                  @method('PUT')
                <textarea name="comment" id="" cols="30" rows="10" class="form-control">{{$comment->comment}}</textarea>
                <span class="text-danger">@error('comment'){{ $message }}@enderror</span>
              </div>
        
              <!-- Modal footer -->
              <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-success">Submit</button>
              </div>
              </form>
        
            </div>
          </div>
        </div>
        <!-- The Modal END -->
                          @endforeach
                      </div>
                  </div>
        
        
              </div>
          </div>
       </div>
      </main>
    </div>
  </div>

@endsection