Blogging/routes/web.php
<?php

use App\Http\Controllers\Admin\AdminAuthController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\GuestPostController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\User\UserAuthController;
use App\Http\Controllers\User\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [GuestPostController::class, 'index'])->name('index');
Route::get('/view_blog/{post}', [GuestPostController::class, 'show'])->name('view_blog');
Route::resource('/comment', CommentController::class);



Auth::routes();

// USER ROUTES
Route::prefix('user')->name('user.')->group(function(){

    Route::middleware(['guest:web'])->group(function(){
        Route::view('/login', 'dashboard.user.login')->name('login');
        Route::view('/register', 'dashboard.user.register')->name('register');
        Route::post('/create', [UserAuthController::class, 'create'])->name('create');
        Route::post('/login', [UserAuthController::class, 'submit'])->name('submit');

    });

    Route::middleware(['auth:web'])->group(function(){
        Route::get('/home', [UserController::class, 'countShow'])->name('home');
        Route::resource('/blog', PostController::class);
        Route::post('/logout', [UserAuthController::class, 'logout'])->name('logout');
        Route::get('your-posts', [UserController::class, 'blogShow'])->name('your_posts');
        // Route::view('create-blog', 'dashboard.user.create_blog')->name('create_blog');
    });
});

// ADMIN ROUTES
Route::prefix('admin')->name('admin.')->group(function(){
       
    Route::middleware(['guest:admin'])->group(function(){
          Route::view('/login','dashboard.admin.login')->name('login');
          Route::post('/login',[AdminAuthController::class,'submit'])->name('submit');
    });

    Route::middleware(['auth:admin'])->group(function(){
        Route::view('/home','dashboard.admin.home')->name('home');
        Route::get('/manage_posts', [AdminController::class, 'show_posts'])->name('manage_posts');
        Route::get('/manage_users', [AdminController::class, 'show_users'])->name('manage_users');
        Route::get('/single_post/{id}', [AdminController::class, 'single_post'])->name('single_post');
        Route::delete('/post_delete/{id}', [AdminController::class, 'post_delete'])->name('post_delete');
        Route::delete('/user_delete/{id}', [AdminController::class, 'user_delete'])->name('user_delete');
        Route::post('/post_status/{id}', [AdminController::class, 'post_status'])->name('post_status');
        Route::get('/day-wise-report', [AdminController::class, 'report_get'])->name('report_get');
        // Route::post('/day-wise-report', [AdminController::class, 'report_result'])->name('report_result');
        Route::post('/logout',[AdminAuthController::class,'logout'])->name('logout');
    });

});

Blogging/app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function posts()
    {
    return $this->hasMany(Post::class);
}

public function comments()
{
    return $this->hasManyThrough(Comment::class, Post::class);
}
    
}

Blogging/app/Http/Controllers/User/UserAuthController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
class UserAuthController extends Controller
{
    function create(Request $request){
        //Validate Inputs
        $request->validate([
            'name'=>'required',
            'email'=>'required|email|unique:users,email',
            'password'=>'required|min:5|max:30',
            'cpassword'=>'required|min:5|max:30|same:password'
        ]);

        User::create([
            'name' => $request->name,
            'email' => $request->email,
            'password' => Hash::make($request->password),
        ]);
        return redirect()->back()->with('success','You are now registered successfully');
    }

    function submit(Request $request){
        //Validate inputs
        $request->validate([
           'email'=>'required|email|exists:users,email',
           'password'=>'required|min:5|max:30'
        ],[
            'email.exists'=>'This email is not exists on users table'
        ]);

        $creds = $request->only('email','password');
        if( Auth::guard('web')->attempt($creds) ){
            return back();
        }else{
            return redirect()->route('user.login')->with('fail','Incorrect credentials');
        }
    }

    function logout(){
        Auth::guard('web')->logout();
        return redirect('/');
    }

}

Blogging/app/Http/Controllers/User/UserController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Models\Comment;
use App\Models\Post;
use Illuminate\Http\Request;
use App\Models\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    // function create(Request $request){
    //     //Validate Inputs
    //     $request->validate([
    //         'name'=>'required',
    //         'email'=>'required|email|unique:users,email',
    //         'password'=>'required|min:5|max:30',
    //         'cpassword'=>'required|min:5|max:30|same:password'
    //     ]);

    //     User::create([
    //         'name' => $request->name,
    //         'email' => $request->email,
    //         'password' => Hash::make($request->password),
    //     ]);
    //     return redirect()->back()->with('success','You are now registered successfully');
    // }

    // function check(Request $request){
    //     //Validate inputs
    //     $request->validate([
    //        'email'=>'required|email|exists:users,email',
    //        'password'=>'required|min:5|max:30'
    //     ],[
    //         'email.exists'=>'This email is not exists on users table'
    //     ]);

    //     $creds = $request->only('email','password');
    //     if( Auth::guard('web')->attempt($creds) ){
    //         return back();
    //     }else{
    //         return redirect()->route('user.login')->with('fail','Incorrect credentials');
    //     }
    // }

    // function logout(){
    //     Auth::guard('web')->logout();
    //     return redirect('/');
    // }

    public function blogShow()
    {
        $user_id = Auth::user()->id;
        $posts = Post::where('user_id', $user_id)->get();
        return view('dashboard.user.your_posts', [
            'posts' => $posts
        ]);;
    }

    public function countShow()
    {
        $user_id = auth()->user()->id;
        $post_count = Post::where('user_id', $user_id)->count();

        $comment_count = Comment::where('user_id', $user_id)->count();
     
        return view('dashboard.user.home', [
            'post_count' => $post_count,
            'comment_count' => $comment_count,
        ]);

    }
}

Blogging/resources/views/dashboard/user/create_blog.blade.php
@extends('layouts.master')
@section('content')
    
<div class="container-fluid">
    <div class="row">
     
      @include('layouts.sidebar')

      <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
       <div class="conatiner">
          <div class="row">
              <div class="col-md-12">
                  @if (Session::get('message'))
                      <div class="alert alert-success">
                          {{ Session::get('message') }}
                      </div>
                  @endif
                  <form action="{{route('user.blog.store')}}" method="post" enctype="multipart/form-data">
                      @csrf
                      <div class="form-group">
                          <label for="title">Title</label>
                          <input type="text" name="title" class="form-control">
                          <span class="text-danger">@error('title'){{ $message }}@enderror</span>
                      </div>
                      <div class="form-group">
                          <label for="title">Description</label>
                          <textarea name="description" id="" cols="30" rows="10" class="form-control"></textarea>
                          <span class="text-danger">@error('description'){{ $message }}@enderror</span>
                      </div>
                      <div class="form-group">
                          <label for="title">Image</label><br>
                          <img id="image" name="image" style="width:300px;" class="normal" />
                          <input type="file" name="image" class="form-control" id="files">
                          <span class="text-danger">@error('image'){{ $message }}@enderror</span>
                      </div>
                      <button type="submit" class="btn btn-primary btn-block">Submit</button>
                  </form>
              </div>
          </div>
       </div>
      </main>
    </div>
  </div>

@endsection

Blogging/resources/views/dashboard/user/edit.blade.php
@extends('layouts.master')
@section('content')
    
<div class="container-fluid">
    <div class="row">
     
      @include('layouts.sidebar')

      <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
       <div class="conatiner">
          <div class="row">
              <div class="col-md-12">
                  @if (Session::get('message'))
                      <div class="alert alert-success">
                          {{ Session::get('message') }}
                      </div>
                  @endif
                  <form action="{{route('user.blog.update', $post->slug)}}" method="post" enctype="multipart/form-data">
                      @csrf
                      @method('PUT')
                      <div class="form-group">
                          <label for="title">Title</label>
                          <input type="text" name="title" class="form-control" value="{{ $post->title }}">
                          <span class="text-danger">@error('title'){{ $message }}@enderror</span>
                      </div>
                      <div class="form-group">
                          <label for="title">Description</label>
                          <textarea name="description" id="" cols="30" rows="10" class="form-control">{{ $post->description }}</textarea>
                          <span class="text-danger">@error('description'){{ $message }}@enderror</span>
                      </div>
                      <div class="form-group">
                          <label for="title">Image</label><br>
                          <img src="{{ asset('storage/images/'.$post->image_path)}}" id="image" style="width:300px;" class="normal" />
                          <input type="file" name="new_image" class="form-control" id="files">
                          <input type="hidden" value="{{$post->image_path}}" name="old_image">
                          <span class="text-danger">@error('image'){{ $message }}@enderror</span>
                      </div>
                      <button type="submit" class="btn btn-primary btn-block">Submit</button>
                  </form>
              </div>
          </div>
       </div>
      </main>
    </div>
  </div>

@endsection

Blogging/resources/views/dashboard/user/home.blade.php
@extends('layouts.master')
@section('content')
    
<div class="container-fluid">
    <div class="row">
     
      @include('layouts.sidebar')

      <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
       <div class="conatiner">
          <div class="row">
              <div class="col-md-12">
                <div class="card-columns">
                  <div class="card bg-primary">
                    <div class="card-body text-center">
                      <p class="card-text text-white">Total {{$post_count}} Posts</p>
                    </div>
                  </div>
                  <div class="card bg-warning">
                    <div class="card-body text-center">
                      <p class="card-text">Some text inside the second card</p>
                    </div>
                  </div>
                  <div class="card bg-success">
                    <div class="card-body text-center">
                      <p class="card-text">Total {{$comment_count}} Comments</p>
                    </div>
                  </div>
                  <div class="card bg-danger">
                    <div class="card-body text-center">
                      <p class="card-text">Some text inside the fourth card</p>
                    </div>
                  </div>
                  <div class="card bg-light">
                    <div class="card-body text-center">
                      <p class="card-text">Some text inside the fifth card</p>
                    </div>
                  </div>
                  <div class="card bg-info">
                    <div class="card-body text-center">
                      <p class="card-text">Some text inside the sixth card</p>
                    </div>
                  </div>
                </div>
              </div>
          </div>
       </div>
      </main>
    </div>
  </div>

@endsection

Blogging/resources/views/dashboard/user/login.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Login</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
</head>
<body>
<div class="container">
        <div class="row">
            <div class="col-md-4 offset-md-4" style="margin-top: 45px;">
                  <h4>User Login</h4><hr>
                  <form action="{{ route('user.submit') }}" method="post">
                    @if (Session::get('fail'))
                        <div class="alert alert-danger">
                            {{ Session::get('fail') }}
                        </div>
                    @endif
                    @csrf
                      <div class="form-group">
                          <label for="email">Email</label>
                          <input type="text" class="form-control" name="email" placeholder="Enter email address" value="{{ old('email') }}">
                          <span class="text-danger">@error('email'){{ $message }}@enderror</span>
                      </div>
                      <div class="form-group">
                          <label for="password">Password</label>
                          <input type="password" class="form-control" name="password" placeholder="Enter password" value="{{ old('password') }}">
                          <span class="text-danger">@error('password'){{ $message }}@enderror</span>
                      </div>
                      <div class="form-group">
                          <button type="submit" class="btn btn-primary">Login</button>
                      </div>
                      <br>
                      <a href="{{ route('user.register') }}">Create new Account</a>
                  </form>
            </div>
        </div>
    </div>
    
</body>
</html>

Blogging/resources/views/dashboard/user/register.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Login</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
</head>
<body>
<div class="container">
        <div class="row">
            <div class="col-md-4 offset-md-4" style="margin-top: 45px;">
                  <h4>User Register</h4><hr>
                  <form action="{{ route('user.create') }}" method="post" autocomplete="off">
                    @if (Session::get('success'))
                         <div class="alert alert-success">
                             {{ Session::get('success') }}
                         </div>
                    @endif
                    @if (Session::get('fail'))
                    <div class="alert alert-danger">
                        {{ Session::get('fail') }}
                    </div>
                    @endif

                    @csrf
                      <div class="form-group">
                          <label for="name">Name</label>
                          <input type="text" class="form-control" name="name" placeholder="Enter full name" value="{{ old('name') }}">
                          <span class="text-danger">@error('name'){{ $message }} @enderror</span>
                      </div>
                      <div class="form-group">
                        <label for="email">Email</label>
                        <input type="text" class="form-control" name="email" placeholder="Enter email address" value="{{ old('email') }}">
                        <span class="text-danger">@error('email'){{ $message }} @enderror</span>
                    </div>
                      <div class="form-group">
                          <label for="password">Password</label>
                          <input type="password" class="form-control" name="password" placeholder="Enter password" value="{{ old('password') }}">
                          <span class="text-danger">@error('password'){{ $message }} @enderror</span>
                      </div>
                      <div class="form-group">
                        <label for="cpassword">Confirm Password</label>
                        <input type="password" class="form-control" name="cpassword" placeholder="Enter confirm password" value="{{ old('cpassword') }}">
                        <span class="text-danger">@error('cpassword'){{ $message }} @enderror</span>
                    </div>
                      <div class="form-group">
                          <button type="submit" class="btn btn-primary">Register</button>
                      </div>
                      <br>
                      <a href="{{ route('user.login') }}">I already have an account</a>
                  </form>
            </div>
        </div>
    </div>
</body>
</html>

Blogging/resources/views/dashboard/user/view.blade.php
@extends('layouts.master')
@section('content')
    
<div class="container-fluid">
    <div class="row">
     
      @if (auth('web')->check())
      @include('layouts.sidebar')
      @endif

      <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
       <div class="conatiner">
          <div class="row">
           
              <div class="col-md-12">
                @if (Session::get('message'))
                <div class="alert alert-success">
                    {{ Session::get('message') }}
                </div>
            @endif
                <div class="jumbotron">
                    <div class="container">
                      <h1 class="display-3">{{$post->title}}</h1>
                      <p>Posted By: {{ ucfirst($post->user->name) }}</p>
                      <p>Published On: {{ date('jS M Y', strtotime($post->created_at)) }}</p>
                      @if (isset(Auth::user()->id) && Auth::user()->id == $post->user_id)
                      <form action="{{route('user.blog.destroy', $post->slug)}}" method="post">
                        @csrf
                        @method('delete')
                       <button type="submit" class="btn btn-danger">Delete Blog</button>
                      </form>                          
                      @endif
                      <hr>
                      <p>{{$post->description}}</p>
                      <hr>
                      @auth
                      <form action="{{route('comment.store')}}" method="post">
                        @csrf
                        
                        <div class="form-group">
                            <label for="title">Comment</label>
                            <textarea name="comment" id="" cols="30" rows="10" class="form-control"></textarea>
                            <span class="text-danger">@error('comment'){{ $message }}@enderror</span>
                            <input type="hidden" name="post_id" value="{{$post->id}}">
                        </div>
                        <button type="submit" class="btn btn-primary btn-block">Submit</button>
                    </form>
                      @endauth
                      @guest
                          <h6 style="text-align: center; padding-top:15px">Please <a href="{{route('user.login')}}"><b>Log in</b></a> to comment<h6>
                      @endguest
                    </div>
                  </div>
                  <h4>Comments</h4>
                  @foreach ($post->comments as $comment)
                  <div class="card mb-2">
                    <div class="card-body">
                      <h4 class="card-title">{{ucfirst($comment->user->name)}}</h4>
                      <p class="card-text">{{$comment->comment}}</p>
                       @if (isset(Auth::user()->id) && Auth::user()->id == $comment->user_id)
                       <button type="submit" class="btn btn-success btn-sm" data-toggle="modal" data-target="#myModal{{$comment->id}}">Edit</button>
                       <form action="{{route('comment.destroy', $comment->id)}}" method="post">
                         @csrf
                         @method('delete')
                         <button type="submit" class="btn btn-danger btn-sm mt-2">Delete</button>
                      </form>                          
                      @endif
                    </div>
                  </div>
                  <!-- The Modal -->
<div class="modal" id="myModal{{$comment->id}}">
  <div class="modal-dialog">
    <div class="modal-content">

      <!-- Modal Header -->
      <div class="modal-header">
        <h4 class="modal-title">Your Comment</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>

      <!-- Modal body -->
      <div class="modal-body">
        <form action="{{route('comment.update', $comment->id)}}" method="post">
          @csrf
          @method('PUT')
        <textarea name="comment" id="" cols="30" rows="10" class="form-control">{{$comment->comment}}</textarea>
        <span class="text-danger">@error('comment'){{ $message }}@enderror</span>
      </div>

      <!-- Modal footer -->
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-success">Submit</button>
      </div>
      </form>

    </div>
  </div>
</div>
<!-- The Modal END -->
                  @endforeach
              </div>
          </div>


      </main>
    </div>
  </div>

@endsection

Blogging/resources/views/dashboard/user/your_posts.blade.php
@extends('layouts.master')
@section('content')
    
<div class="container-fluid">
    <div class="row">
     
      @include('layouts.sidebar')

      <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
       <div class="conatiner">
          <div class="row">
              <div class="col-md-12">
                @if (Session::get('message'))
                <div class="alert alert-success">
                    {{ Session::get('message') }}
                </div>
                @endif
                <div class="album py-5 bg-light">
                  <div class="container">
                    <div class="row">
                      @foreach ($posts as $post)
                      <div class="col-md-4">
                        <div class="card mb-4 box-shadow">
                          <img class="card-img-top" src="{{ asset('storage/images/'.$post->image_path)}}" height="200px">                          
                          <div class="card-body">
                            <h6 class="card-text">{{ $post->title }}</h6>
                            <p>{{ \Illuminate\Support\Str::limit($post->description, 30, $end='...')}}</p>
                            <div class="d-flex justify-content-between align-items-center">
                              <div class="btn-group">
                                <a href="{{route('user.blog.show', $post->slug)}}" class="btn btn-sm btn-outline-secondary">View</a>
                                <a href="{{route('user.blog.edit', $post->slug)}}" class="btn btn-sm btn-outline-secondary">Edit</a>
                              </div>
                              <small class="text-muted">{{ date('jS M Y', strtotime($post->created_at)) }}</small>
                            </div>
                          </div>
                        </div>
                      </div>
                      @endforeach
                    </div>
                  </div>
                </div>
      </main>
    </div>
  </div>

@endsection