Blogging/routes/web.php
<?php

use App\Http\Controllers\Admin\AdminAuthController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\GuestPostController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\User\UserAuthController;
use App\Http\Controllers\User\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [GuestPostController::class, 'index'])->name('index');
Route::get('/view_blog/{post}', [GuestPostController::class, 'show'])->name('view_blog');
Route::resource('/comment', CommentController::class);



Auth::routes();

// USER ROUTES
Route::prefix('user')->name('user.')->group(function(){

    Route::middleware(['guest:web'])->group(function(){
        Route::view('/login', 'dashboard.user.login')->name('login');
        Route::view('/register', 'dashboard.user.register')->name('register');
        Route::post('/create', [UserAuthController::class, 'create'])->name('create');
        Route::post('/login', [UserAuthController::class, 'submit'])->name('submit');

    });

    Route::middleware(['auth:web'])->group(function(){
        Route::get('/home', [UserController::class, 'countShow'])->name('home');
        Route::resource('/blog', PostController::class);
        Route::post('/logout', [UserAuthController::class, 'logout'])->name('logout');
        Route::get('your-posts', [UserController::class, 'blogShow'])->name('your_posts');
        // Route::view('create-blog', 'dashboard.user.create_blog')->name('create_blog');
    });
});

// ADMIN ROUTES
Route::prefix('admin')->name('admin.')->group(function(){
       
    Route::middleware(['guest:admin'])->group(function(){
          Route::view('/login','dashboard.admin.login')->name('login');
          Route::post('/login',[AdminAuthController::class,'submit'])->name('submit');
    });

    Route::middleware(['auth:admin'])->group(function(){
        Route::view('/home','dashboard.admin.home')->name('home');
        Route::get('/manage_posts', [AdminController::class, 'show_posts'])->name('manage_posts');
        Route::get('/manage_users', [AdminController::class, 'show_users'])->name('manage_users');
        Route::get('/single_post/{id}', [AdminController::class, 'single_post'])->name('single_post');
        Route::delete('/post_delete/{id}', [AdminController::class, 'post_delete'])->name('post_delete');
        Route::delete('/user_delete/{id}', [AdminController::class, 'user_delete'])->name('user_delete');
        Route::post('/post_status/{id}', [AdminController::class, 'post_status'])->name('post_status');
        Route::get('/day-wise-report', [AdminController::class, 'report_get'])->name('report_get');
        // Route::post('/day-wise-report', [AdminController::class, 'report_result'])->name('report_result');
        Route::post('/logout',[AdminAuthController::class,'logout'])->name('logout');
    });

});

Blogging/resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav me-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ms-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

Blogging/resources/views/layouts/master.blade.php
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <title>Dashboard Template for Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/dashboard/">

    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/docs/4.0/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="dashboard.css" rel="stylesheet">

    <link href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css" rel="stylesheet">

    
  </head>

  <body>
    {{-- <nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0">
      <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="/">Company name</a>
      <ul class="navbar-nav px-3">
        <li class="nav-item text-nowrap">
            @if (auth('web')->check())
            <a class="nav-link" href="{{ route('user.logout') }}" onclick="event.preventDefault();document.getElementById('logout-form').submit();">Logout</a>
            <form action="{{ route('user.logout') }}" method="post" class="d-none" id="logout-form">@csrf</form>      
            @else
            <a href="{{ route('user.login') }}" class="text-sm text-gray-700 dark:text-gray-500 underline">Log in</a>
            <a href="{{ route('user.register') }}" class="ml-4 text-sm text-gray-700 dark:text-gray-500 underline">Register</a>
            @endif
        </li>
      </ul>
    </nav> --}}
    <nav class="navbar navbar-expand-md navbar-dark sticky-top bg-dark">
      <a class="navbar-brand" href="/">Navbar</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
        @if (auth('web')->check())
          <li class="nav-item active">
            <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              {{auth()->user()->name}}
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{{route('user.home')}}">Dashboard</a>
              <a class="dropdown-item" href="{{route('user.blog.create')}}">Create Blog</a>
              <a class="dropdown-item" href="{{route('user.your_posts')}}">Your Posts</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{{ route('user.logout') }}" onclick="event.preventDefault();document.getElementById('logout-form').submit();">Logout</a>
              <form action="{{ route('user.logout') }}" method="post" class="d-none" id="logout-form">@csrf</form>
            </div>
          </li>
        @elseif(auth('admin')->check())
        <li class="nav-item active">
          <a class="nav-link" href="{{ route('admin.logout') }}" onclick="event.preventDefault();document.getElementById('logout-form').submit();">Logout <span class="sr-only">(current)</span></a>
          <form action="{{ route('admin.logout') }}" method="post" class="d-none" id="logout-form">@csrf</form>
        </li>
        </ul>
      </div>
      @else
            <ul class="navbar-nav ml-auto">
              <li><a href="{{ route('user.login') }}" class="nav-link text-sm text-gray-700 dark:text-gray-500 underline">Log in</a></li>
              <li><a href="{{ route('user.register') }}" class="nav-link ml-4 text-sm text-gray-700 dark:text-gray-500 underline">Register</a></li>
            </ul>
      @endif
    </nav>

    @yield('content')
    
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>'
    <script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
    <script>
      $(document).ready( function () {
    $('#myTable').DataTable(paging: false);
      } );
    </script>
    <script>
      $(document).ready( function () {
    $('#myTable_manage').DataTable();
      } );
    </script>

    <!-- Icons -->
    <script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
    <script>
      feather.replace()
    </script>

    <!-- Graphs -->
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.7.1/dist/Chart.min.js"></script>
    <script>
      var ctx = document.getElementById("myChart");
      var myChart = new Chart(ctx, {
        type: 'line',
        data: {
          labels: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
          datasets: [{
            data: [15339, 21345, 18483, 24003, 23489, 24092, 12034],
            lineTension: 0,
            backgroundColor: 'transparent',
            borderColor: '#007bff',
            borderWidth: 4,
            pointBackgroundColor: '#007bff'
          }]
        },
        options: {
          scales: {
            yAxes: [{
              ticks: {
                beginAtZero: false
              }
            }]
          },
          legend: {
            display: false,
          }
        }
      });
    </script>

    <script>
        document.getElementById("files").onchange = function () {
    var reader = new FileReader();
    
    reader.onload = function (e) {
        document.getElementById("image").src = e.target.result;
        };
    reader.readAsDataURL(this.files[0]);
};

    </script>
  </body>
</html>

Blogging/resources/views/layouts/sidebar.blade.php
<nav class="col-md-2 d-none d-md-block bg-light sidebar">
    <div class="sidebar-sticky">
      <ul class="nav flex-column">
        @if (auth('web')->check())
        <li class="nav-item">
          <a class="nav-link active" href="{{route('user.home')}}">
            <span data-feather="home"></span>
            Dashboard <span class="sr-only">(current)</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ route('user.your_posts') }}">
            <span data-feather="book"></span>
            Your Posts
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ route('user.blog.create') }}">
            <span data-feather="file-plus"></span>
            Create new Blog
          </a>
        </li>
        @elseif(auth('admin')->check())
        <li class="nav-item">
          <a class="nav-link active" href="">
            <span data-feather="home"></span>
            Dashboard <span class="sr-only">(current)</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{route('admin.manage_posts')}}">
            <span data-feather="book"></span>
            Manage Posts
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{route('admin.manage_users')}}">
            <span data-feather="user"></span>
            Manage Users
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{route('admin.report_get')}}">
            <span data-feather="user"></span>
            Day wise Reports
          </a>
        </li>
        @endif
      </ul>
    </div>
  </nav>